---
apiVersion: v1
kind: Pod
metadata:
    name: myapp-nginx
    labels:
            name: applogin
            version: v1
spec:
    containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
    name: myapp-httpd
    labels:
            name: applogin
            version: v2
spec:
    containers:
        - name: myapp
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP

