apiVersion: v1
kind: Service
metadata: 
        name: myapp-svc
spec:
        selector:
                name: applogin 
                version: v1
        ports:
                - name: nginxport
                  port: 80    #nginx port running inside the pod
                  nodePort: 30080
                  protocol: TCP
        type: NodePort
